### ISSUE TITLE
Problème sur la connexion des meta-données dans la dernière version du script

### ISSUE THREAD

**Issue by tommv** [medialab/bibliotools3.0#1]
En les analysant avec les doctorants de Leuven, on a trouvé un truc bizarre sur les cartes que tu m'a envoyé jeudi dernier.
Les références spatialisent bien, mais il y a un problème sur le meta-données.
Sur pas mal des cartes (notamment celles des dernières tranches temporelles), quasiment tous les nœuds des meta-données se retrouvent au centre (car uniformément liés à toutes les parties du graphe de références).

Au début je croyais qu'il s'agissait d'un problème des seuils, mais puis on a lancé l'extraction des même cartes (avec les mêmes seuils) sur l'ordi de Kari et on ne retrouve pas le même problème (les meta-données au contraire se spatialisent bien où on s'attendrait de les trouver).

Vu que le problème semble concerner seulement les dernières tranches temporelles, je me demande si cela n'est pas du à la parallélisation.

**Comment by paulgirard** [comment]
Bug couldn't be replicated. the multiproc version has been tested and no problem in it.
Added it as default script in README.
